### ISSUE TITLE
Auto refresh feature

### ISSUE THREAD

**Issue by fayasnoushad** [AbirHasan2005/Emoji-Captcha-Bot#2]
Please add auto refresh feature.

If the user not leaved from group. Then auto refresh after time limit. Else delete.

**Comment by jigarvarma2k20** [comment]
> Please add auto refresh feature.
> 
> If the user not leaved from group. Then auto refresh after time limit. Else delete.

Explain

**Comment by fayasnoushad** [comment]
> > Please add auto refresh feature.
> > If the user not leaved from group. Then auto refresh after time limit. Else delete.
> 
> Explain

So many users will not prove it. So it needs a feature that refreshes automatically.

**Comment by AbirHasan2005** [comment]
Refresh what? 🤔🤔🤔

**Comment by fayasnoushad** [comment]
> Refresh what? thinkingthinkingthinking

Refresh the captcha message for non-proved users.

**Comment by AbirHasan2005** [comment]
Oh got it. I will try to get a way to do that.

**Comment by fayasnoushad** [comment]
> Oh got it. I will try to get a way to do that.

Hmm
